AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Bravy-Broker API

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Function
      CodeUri: src/update_market_orders
      Handler: update_market_orders.handler
      Runtime: python3.13
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Layers:
        - !Ref ServicesLayer
      Environment:
        Variables:
          EVE_CLIENT_ID: UNSET
          EVE_SECRET_KEY: UNSET
          REFRESH_TOKEN: UNSET
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}
  ServicesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Layer ${ResourceName}
        - ResourceName: ServicesLayer
      ContentUri: src/services-layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.13